In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
arr

array([1, 2, 3])

In [8]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

x축 y축으로 2차행렬이다.

In [10]:
mymatrix = np.array(mylist)

In [11]:
mymatrix.shape

(3, 3)

In [13]:
mynewmatrix = np.array(mylist)

# 내장함수

In [17]:
np.arange(0,10) # 시작인덱스는 포함되지만 스톱인덱스는 포함되지 않는다.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# 스텝사이즈 설정하기
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.zeros(5) #점은 부동소수점이다.

array([0., 0., 0., 0., 0.])

In [22]:
type(0.0) # 유형은 정수가 아닌 실수로 표시된다. type(0.)도 마찬가지다. 0으로 구성된 1차원 배열


float

작업중 부동소수점을 많이 맞이하게 된다면 numpy다.

In [23]:
# 튜플을 입력할 수 있다.
np.zeros((4,10)) # 4는 행의 수, 10은 열의 수

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

넘파이 연산

In [25]:
# 데이터를 변경하려면
np.ones((5,5)) +4 # 이렇게하면 4씩 다 더한 값을 얻을 수 있다.

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [26]:
np.ones(4) * 100 # 배열 안의 모든 요소들에 대해서 계산을 할 수 있다.

array([100., 100., 100., 100.])

넘파이 연산이 아닐경우

In [27]:
[1,1,1,1]*100 # 연산이 수행되지 않고 리스트 100개가 생긴다.

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


특정 간격에 따라 일정하게 간격이 생기는 연산<br>
np.linspace(시작값,끝나는값, 원하는숫자의개수)

In [28]:
np.linspace(0,10,3) # 0~10까지 일정한 간격으로 배치된 3개의 숫자

array([ 0.,  5., 10.])

In [29]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [30]:
len(np.linspace(0,10,20)) # 개수를 확인해보면 20개가 맞다.

20

단위행렬 생성 np.eye()

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])