In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 넘파이 인덱싱<br>
일반적인 파이썬 리스트 인덱싱과 같다.

In [4]:
arr[8] 

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

# 함수와 연산의 브로드캐스트

In [7]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [8]:
new_arr = arr/2

In [9]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# 재할당할 경우 기존 array에 영향을 준다. <br>
슬라이스를 기반으로 재할당, 브로드캐스팅을 수행하면 기존 배열에도 가져올 수 있다.


In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr = arr[0:6]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:] =99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
#따라서 영향을 받지 않으려면 변수명을 새로 생성해야한다.
arr_copy=arr.copy()

In [19]:
arr_copy[:] = 10000

In [20]:
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# 2차원 행렬에 대한 인덱싱

In [23]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d.shape

(3, 3)

In [26]:
arr_2d[1] #2번째 행을 나타낸다.

array([20, 25, 30])

In [27]:
arr_2d[1][1] # 2번째 행의 2번째 값을 가져오려면 이렇게 해야한다.

25

In [28]:
arr_2d[1,1]

25

In [29]:
arr_2d[2,2]

45

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d[:2] # 슬라이스가 마지막값인 2를 포함하지 않기 때문에 1행과 2행이 출력된다.

array([[ 5, 10, 15],
       [20, 25, 30]])

In [33]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [34]:
arr =np.arange(1,11)

In [35]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

조건부 선택을 수행하기

In [37]:
bool_arr = arr>4

In [39]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr[arr ==2]

array([2])

In [41]:
arr[arr<=6]

array([1, 2, 3, 4, 5, 6])