In [4]:
import numpy as np

In [5]:
arr = np.arange(0,10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [8]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [9]:
arr **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
(arr+2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

0으로 나누게 되면 넘파이는 연산은 완료하되 경고문구가 출력된다.

In [13]:
1/arr # 1/0이면 inf가 발생

C:\Users\pshye\AppData\Local\Temp\ipykernel_5876\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
arr /arr #0/0은 nan

C:\Users\pshye\AppData\Local\Temp\ipykernel_5876\591710190.py:1: RuntimeWarning: invalid value encountered in divide
  arr /arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

제곱근 구하기

In [15]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

log 계산

In [16]:
np.log(arr) #0의 로그는 마이너스 무한대이다.

C:\Users\pshye\AppData\Local\Temp\ipykernel_5876\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [17]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [18]:
arr.sum()

45

In [19]:
arr.mean()

4.5

In [20]:
arr.max()

9

In [21]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [22]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr_2d.shape

(3, 4)

In [24]:
arr_2d.sum()


78

In [25]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [26]:
arr_2d.sum(axis=0) # 수직축으로 계산

array([15, 18, 21, 24])

In [27]:
arr_2d.sum(axis=1)# 수평축으로 계산

array([10, 26, 42])