In [1]:
import numpy as np

랜덤함수

In [2]:
np.random.rand(1)

array([0.80761604])

In [4]:
np.random.rand(5)

array([0.71774376, 0.7034643 , 0.80666817, 0.90891465, 0.76551961])

In [3]:
np.random.rand(5,5)

array([[0.89630671, 0.15209392, 0.13714449, 0.81545668, 0.21765246],
       [0.66017289, 0.41126258, 0.4090372 , 0.14500821, 0.93771816],
       [0.30330635, 0.53162479, 0.83435434, 0.38692291, 0.01793711],
       [0.9962645 , 0.7779678 , 0.93278916, 0.67736418, 0.29976056],
       [0.25403822, 0.3035673 , 0.47124937, 0.01217346, 0.88649651]])

In [5]:
np.random.randn(1) # 표준 정규분포에서 하나 이상의 샘플이 반환
# 표준 정규 분포의 평균은 0이고 표준편차는 1이다.

array([-2.32669079])

In [6]:
np.random.normal

<function RandomState.normal>

In [7]:
np.random.randint(1,100,10)

array([36, 53,  4, 72, 76, 56, 69, 90, 97, 70])

난수 생성시 seed 설정<br>
random.seed는 난수를 어떤 설정으로 생성할건지 설정하는 것이다.<br>
하지만 seed와 rand가 같은 실행에 있어야 같은 값이 나온다.

In [9]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [10]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [11]:
arr = np.arange(25)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
ranarr = np.random.randint(0,50,10)

In [14]:
ranarr

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

shape을 변경할 수 있다.

In [17]:
# arr의 shape 변경 기존 1차우너 배열
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
ranarr

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

In [21]:
ranarr.max()

48

In [22]:
ranarr.min()

10

### argmax(), argmin()

In [24]:
ranarr.argmax() #해당 array에서 인덱스 위치를 찾는다.

1

In [25]:
ranarr.argmin() #해당 array에서 인덱스 위치를 찾는다.

6